[options]
admin_passwd = $pbkdf2-sha512$600000$EQLgvNd6z1nrXcvZ.z.n1A$f/VM9/fQHbfCd86YVu8bdmKrZCzgyfO0ZxWeaUXVNiYEjrPtUDGuew25uNO4ORT3pcd6WkI5G.VfqB5gtpPQXg
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
dev_mode = reload,qweb,werkzeug,xml
test_enable = True
log_level = info

